In [3]:
import warnings
warnings.filterwarnings("ignore")

### Load combined data

In [2]:
import pandas as pd
from pandas import DataFrame
import matplotlib.pyplot as plt

In [3]:
comb_df_train = pd.read_csv('./train_data/combined_data.csv', index_col = 0)

In [4]:
comb_df_test = pd.read_csv('./test_data/combined_test.csv', index_col = 0)

In [5]:
comb_df = comb_df_test.combine_first( comb_df_train )

In [6]:
tmp = comb_df.transpose()
tmp

,cd19_ENSG00000000419.12,cd19_ENSG00000000938.12,cd19_ENSG00000001461.16,cd19_ENSG00000001497.16,cd19_ENSG00000001629.9,cd19_ENSG00000001631.14,cd19_ENSG00000002549.12,cd19_ENSG00000002822.15,cd19_ENSG00000002919.14,cd19_ENSG00000003056.7,...,nasal_ENSG00000280755.1,nasal_ENSG00000280778.1,nasal_ENSG00000280832.1,nasal_ENSG00000281383.1,nasal_ENSG00000281467.1,nasal_ENSG00000281649.1,nasal_ENSG00000281991.1,nasal_ENSG00000282031.1,nasal_ENSG00000282432.1,severity_score
101,38.856455,55.340934,26.318800,53.256922,24.246088,27.531098,80.423126,10.012680,19.416264,449.331940,...,26.507794,-2.321184,54.369508,-1.006372,90.161287,9.212198,3.587722,234.386930,9.734210,7.617048
102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.752152,2.406203,1.107680,11.735275,-3.925289,16.398318,38.526833,198.249318,-3.379815,NaN
103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.894531,31.021615,9.169651,20.842500,-2.638925,14.382949,15.590822,207.078942,-0.254971,NaN
104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.057942,4.008020,16.364680,5.115424,27.004055,27.775840,37.542737,138.979931,-4.837502,4.983152
105,39.856980,43.076633,22.426250,45.702074,14.704561,21.596467,125.331892,18.514680,16.264019,243.135221,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.298928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.050281,50.430422,-1.296370,19.328475,-4.837502,11.420940,10.032910,148.911838,-4.837502,3.546627
236,18.269733,72.082627,21.983788,46.289715,47.539140,42.851128,190.041003,16.907751,24.427166,156.318390,...,63.986158,3.623853,20.440679,0.382578,14.244901,12.181748,12.014473,192.953059,25.117467,0.621695
237,23.246888,36.075311,7.351720,33.499505,53.842621,59.982620,45.580721,94.345319,16.189853,140.140171,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.922664
238,45.194342,68.146717,20.725060,38.015449,52.614699,14.847110,99.249788,-2.935020,16.108770,302.436996,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.989781
239,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#tmp.plot(x ='cd19_ENSG00000000419.12', y='severity_score', kind = 'scatter')
#plt.show()

In [8]:
#tmp.plot(x ='cd19_ENSG00000000419.12', y='severity_score', kind = 'bar')
#plt.show()

### Data Imputation

In [9]:
from statsmodels.imputation.mice import MICEData

In [10]:
feature_list = list(tmp)[0:]
#print(feature_list)

In [11]:
X = tmp[feature_list]
imp = MICEData(X)

In [14]:
filled_data = imp.data
print(len(filled_data))
filled_data.head()

137

,cd19_ENSG00000000419.12,cd19_ENSG00000000938.12,cd19_ENSG00000001461.16,cd19_ENSG00000001497.16,cd19_ENSG00000001629.9,cd19_ENSG00000001631.14,cd19_ENSG00000002549.12,cd19_ENSG00000002822.15,cd19_ENSG00000002919.14,cd19_ENSG00000003056.7,...,nasal_ENSG00000280755.1,nasal_ENSG00000280778.1,nasal_ENSG00000280832.1,nasal_ENSG00000281383.1,nasal_ENSG00000281467.1,nasal_ENSG00000281649.1,nasal_ENSG00000281991.1,nasal_ENSG00000282031.1,nasal_ENSG00000282432.1,severity_score
0,38.856455,55.340934,26.318800,53.256922,24.246088,27.531098,80.423126,10.012680,19.416264,449.331940,...,26.507794,-2.321184,54.369508,-1.006372,90.161287,9.212198,3.587722,234.386930,9.734210,7.617048
1,38.799699,70.779560,29.264499,55.746139,29.253274,32.271049,107.301528,19.421827,23.963675,304.470779,...,13.752152,2.406203,1.107680,11.735275,-3.925289,16.398318,38.526833,198.249318,-3.379815,4.518783
2,38.799699,70.779560,29.264499,55.746139,29.253274,32.271049,107.301528,19.421827,23.963675,304.470779,...,22.894531,31.021615,9.169651,20.842500,-2.638925,14.382949,15.590822,207.078942,-0.254971,4.518783
3,38.799699,70.779560,29.264499,55.746139,29.253274,32.271049,107.301528,19.421827,23.963675,304.470779,...,20.057942,4.008020,16.364680,5.115424,27.004055,27.775840,37.542737,138.979931,-4.837502,4.983152
4,39.856980,43.076633,22.426250,45.702074,14.704561,21.596467,125.331892,18.514680,16.264019,243.135221,...,33.736401,11.637600,15.258226,9.363774,31.942221,14.788805,27.887704,149.639517,9.734210,1.298928

In [15]:
filled_data.shape

(137, 24658)

In [16]:
filled_data.to_csv(r'./train_data/filled_data_all.csv', index = True, header=True)

# -------------------------------------------------------------------------------

In [4]:
df = pd.read_csv('./train_data/filled_data_all.csv', index_col = 0)
df

,cd19_ENSG00000000419.12,cd19_ENSG00000000938.12,cd19_ENSG00000001461.16,cd19_ENSG00000001497.16,cd19_ENSG00000001629.9,cd19_ENSG00000001631.14,cd19_ENSG00000002549.12,cd19_ENSG00000002822.15,cd19_ENSG00000002919.14,cd19_ENSG00000003056.7,...,nasal_ENSG00000280755.1,nasal_ENSG00000280778.1,nasal_ENSG00000280832.1,nasal_ENSG00000281383.1,nasal_ENSG00000281467.1,nasal_ENSG00000281649.1,nasal_ENSG00000281991.1,nasal_ENSG00000282031.1,nasal_ENSG00000282432.1,severity_score
0,38.856455,55.340934,26.318800,53.256922,24.246088,27.531098,80.423126,10.012680,19.416264,449.331940,...,26.507794,-2.321184,54.369508,-1.006372,90.161287,9.212198,3.587722,234.386930,9.734210,7.617048
1,38.799699,70.779560,29.264499,55.746139,29.253274,32.271049,107.301528,19.421827,23.963675,304.470779,...,13.752152,2.406203,1.107680,11.735275,-3.925289,16.398318,38.526833,198.249318,-3.379815,4.518783
2,38.799699,70.779560,29.264499,55.746139,29.253274,32.271049,107.301528,19.421827,23.963675,304.470779,...,22.894531,31.021615,9.169651,20.842500,-2.638925,14.382949,15.590822,207.078942,-0.254971,4.518783
3,38.799699,70.779560,29.264499,55.746139,29.253274,32.271049,107.301528,19.421827,23.963675,304.470779,...,20.057942,4.008020,16.364680,5.115424,27.004055,27.775840,37.542737,138.979931,-4.837502,4.983152
4,39.856980,43.076633,22.426250,45.702074,14.704561,21.596467,125.331892,18.514680,16.264019,243.135221,...,33.736401,11.637600,15.258226,9.363774,31.942221,14.788805,27.887704,149.639517,9.734210,1.298928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,38.799699,70.779560,29.264499,55.746139,29.253274,32.271049,107.301528,19.421827,23.963675,304.470779,...,-0.050281,50.430422,-1.296370,19.328475,-4.837502,11.420940,10.032910,148.911838,-4.837502,3.546627
133,18.269733,72.082627,21.983788,46.289715,47.539140,42.851128,190.041003,16.907751,24.427166,156.318390,...,63.986158,3.623853,20.440679,0.382578,14.244901,12.181748,12.014473,192.953059,25.117467,0.621695
134,23.246888,36.075311,7.351720,33.499505,53.842621,59.982620,45.580721,94.345319,16.189853,140.140171,...,33.736401,11.637600,15.258226,9.363774,31.942221,14.788805,27.887704,149.639517,9.734210,4.922664
135,45.194342,68.146717,20.725060,38.015449,52.614699,14.847110,99.249788,-2.935020,16.108770,302.436996,...,33.736401,11.637600,15.258226,9.363774,31.942221,14.788805,27.887704,149.639517,9.734210,7.989781
136,38.799699,70.779560,29.264499,55.746139,29.253274,32.271049,107.301528,19.421827,23.963675,304.470779,...,33.736401,11.637600,15.258226,9.363774,31.942221,14.788805,27.887704,149.639517,9.734210,4.518783

In [5]:
std = df.loc[:,"severity_score"].std()
std

2.066306886097156

In [6]:
avg = std = df.loc[:,"severity_score"].mean()
avg

4.569974372262772

In [7]:
tmp = pd.read_csv('./train_data/filled_data_all.csv', index_col = 0)
y_before = tmp[tmp.columns[-1]]

### Normalization

In [8]:
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.decomposition import PCA
from sklearn import preprocessing
from sklearn import utils
from sklearn.preprocessing import StandardScaler

In [9]:
scal = StandardScaler()
df = scal.fit_transform(df)
df = pd. DataFrame(df)

In [10]:
feature = list(df)[0:-1]
X = df[feature]
y = df[df.columns[-1]]
y

0      1.480059
1     -0.024865
2     -0.024865
3      0.200693
4     -1.588849
         ...
132   -0.497072
133   -1.917803
134    0.171312
135    1.661107
136   -0.024865
Name: 24657, Length: 137, dtype: float64

In [11]:
X = StandardScaler().fit_transform(X)
type(X)

numpy.ndarray

In [12]:
feat_cols = ['feature'+str(i) for i in range(X.shape[1])]

In [13]:
normalized_data = pd.DataFrame(X,columns=feat_cols)
normalized_data['score'] = y

In [14]:
normalized_data.head()

,feature0,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,...,feature24648,feature24649,feature24650,feature24651,feature24652,feature24653,feature24654,feature24655,feature24656,score
0,0.024195,-0.595581,-0.268840,-0.114402,-0.414022,-0.370464,-0.606081,-0.477375,-0.661426,1.691496,...,-0.273148,-0.966157,2.635572,-1.216972,1.017995,-0.873492,-1.942849,2.153681,0.005307,1.480059
1,0.019075,0.003637,-0.005734,0.013134,0.003693,0.007518,-0.007040,-0.005823,-0.014546,-0.000127,...,-0.759260,-0.640716,-0.988034,0.288321,-0.611172,0.268482,0.847671,1.225785,-0.416442,-0.024865
2,0.019075,0.003637,-0.005734,0.013134,0.003693,0.007518,-0.007040,-0.005823,-0.014546,-0.000127,...,-0.410848,1.329214,-0.439547,1.364245,-0.588898,-0.051788,-0.984184,1.452501,-0.315946,-0.024865
3,0.019075,0.003637,-0.005734,0.013134,0.003693,0.007518,-0.007040,-0.005823,-0.014546,-0.000127,...,-0.518949,-0.530444,0.049958,-0.493745,-0.075611,2.076526,0.769073,-0.296060,-0.463321,0.200693
4,0.114466,-1.071595,-0.616517,-0.501477,-1.210005,-0.843715,0.394804,-0.051286,-1.109841,-0.716376,...,0.002331,-0.005212,-0.025318,0.008153,0.009896,0.012708,-0.002056,-0.022357,0.005307,-1.588849

In [15]:
df = normalized_data

# -------------------------------------------------------

In [16]:
#df.plot(x ='feature100', y='score', kind = 'scatter')
#plt.show()

# -------------------------------------------------------

In [17]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import mean_squared_error
import numpy as np



for i in range(2,100):
    pca_data = PCA(n_components = i)
    
    columns_name = []
    for j in range(1, i+1):
        name = 'pc '+ str(j)
        columns_name.append(name)
        
    principalComponents = pca_data.fit_transform(normalized_data.iloc[:,:-1])
    
    principal_data_Df = pd.DataFrame(data = principalComponents
             , columns = columns_name)
    principal_data_Df['y'] = y
    #print(principal_data_Df.head())
    print('number: ', i)
    if sum(pca_data.explained_variance_ratio_)>0.9:
        print('Explained variation per principal component: {}'.format(pca_data.explained_variance_ratio_))
        break

number:  2
number:  3
number:  4
number:  5
number:  6
number:  7
number:  8
number:  9
number:  10
number:  11
number:  12
number:  13
number:  14
number:  15
number:  16
number:  17
number:  18
number:  19
number:  20
number:  21
number:  22
number:  23
number:  24

KeyboardInterrupt:

In [18]:
pca_data = PCA(n_components = 137)
principalComponents = pca_data.fit_transform(normalized_data.iloc[:,:-1])

In [19]:
columns_name = []
for j in range(1, 138):
    name = 'pc '+ str(j)
    columns_name.append(name)
print(columns_name)

['pc 1', 'pc 2', 'pc 3', 'pc 4', 'pc 5', 'pc 6', 'pc 7', 'pc 8', 'pc 9', 'pc 10', 'pc 11', 'pc 12', 'pc 13', 'pc 14', 'pc 15', 'pc 16', 'pc 17', 'pc 18', 'pc 19', 'pc 20', 'pc 21', 'pc 22', 'pc 23', 'pc 24', 'pc 25', 'pc 26', 'pc 27', 'pc 28', 'pc 29', 'pc 30', 'pc 31', 'pc 32', 'pc 33', 'pc 34', 'pc 35', 'pc 36', 'pc 37', 'pc 38', 'pc 39', 'pc 40', 'pc 41', 'pc 42', 'pc 43', 'pc 44', 'pc 45', 'pc 46', 'pc 47', 'pc 48', 'pc 49', 'pc 50', 'pc 51', 'pc 52', 'pc 53', 'pc 54', 'pc 55', 'pc 56', 'pc 57', 'pc 58', 'pc 59', 'pc 60', 'pc 61', 'pc 62', 'pc 63', 'pc 64', 'pc 65', 'pc 66', 'pc 67', 'pc 68', 'pc 69', 'pc 70', 'pc 71', 'pc 72', 'pc 73', 'pc 74', 'pc 75', 'pc 76', 'pc 77', 'pc 78', 'pc 79', 'pc 80', 'pc 81', 'pc 82', 'pc 83', 'pc 84', 'pc 85', 'pc 86', 'pc 87', 'pc 88', 'pc 89', 'pc 90', 'pc 91', 'pc 92', 'pc 93', 'pc 94', 'pc 95', 'pc 96', 'pc 97', 'pc 98', 'pc 99', 'pc 100', 'pc 101', 'pc 102', 'pc 103', 'pc 104', 'pc 105', 'pc 106', 'pc 107', 'pc 108', 'pc 109', 'pc 110', 'pc 111', 'pc 112', 'pc 113', 'pc 114', 'pc 115', 'pc 116', 'pc 117', 'pc 118', 'pc 119', 'pc 120', 'pc 121', 'pc 122', 'pc 123', 'pc 124', 'pc 125', 'pc 126', 'pc 127', 'pc 128', 'pc 129', 'pc 130', 'pc 131', 'pc 132', 'pc 133', 'pc 134', 'pc 135', 'pc 136', 'pc 137']

In [20]:
principal_data_Df = pd.DataFrame(data = principalComponents
             , columns = columns_name)
principal_data_Df['y'] = y

In [21]:
principal_data_Df.head()

,pc 1,pc 2,pc 3,pc 4,pc 5,pc 6,pc 7,pc 8,pc 9,pc 10,...,pc 129,pc 130,pc 131,pc 132,pc 133,pc 134,pc 135,pc 136,pc 137,y
0,152.729636,7.925037,57.089688,27.317618,67.147204,28.235837,-45.914902,-46.550199,16.064417,-54.337975,...,-0.031078,-0.707511,-0.094045,-0.375555,-0.116941,0.025113,2.063870e-14,2.568890e-16,5.537672e-17,1.480059
1,-33.389038,1.248452,6.292687,5.497774,12.787176,-11.837406,-6.634867,0.655378,-1.812856,-3.611270,...,0.916879,-0.959219,-0.222721,-2.805518,-0.108652,0.055487,2.063870e-14,2.568890e-16,5.537672e-17,-0.024865
2,-21.606351,3.619867,11.164855,1.677963,-12.865418,10.606822,8.717023,-8.871282,7.459532,9.347517,...,-9.007833,9.179933,4.797004,3.296211,-0.205297,0.046542,2.063870e-14,2.568890e-16,5.537672e-17,-0.024865
3,-27.995534,-14.952931,-8.396283,0.761634,7.317083,-7.126222,2.137740,6.482903,-11.056900,0.336020,...,-1.871209,-1.525535,-1.111816,0.389803,-0.082187,0.032496,2.063870e-14,2.568890e-16,5.537672e-17,0.200693
4,-4.709871,5.703500,2.731764,-55.218985,-11.624407,1.671493,-3.791983,18.824681,-5.259652,18.190562,...,-0.610791,-0.418609,-0.095408,-0.150033,-0.098861,0.032243,2.063870e-14,2.568890e-16,5.537672e-17,-1.588849

In [22]:
y = principal_data_Df['y']
X = principal_data_Df[columns_name]
    
loo = LeaveOneOut()
loo.get_n_splits(X)


y_pred = []
for train_index, test_index in loo.split(X):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train = X.iloc[train_index]
    X_test = X.iloc[test_index]
    y_train = y.iloc[train_index]
    y_test = y.iloc[test_index]
    #print(y_test)
    
    
    regr = RandomForestRegressor(max_depth=2, random_state=0)
    regr.fit(X_train, y_train)

    #y_pred = regr.predict(X_test)
    y_pred.append(regr.predict(X_test)*std + avg)
    
    #print(test_index, y_pred, y_before.iloc[test_index])
    #mse.append(mean_squared_error(y_test, y_pred))
print(y_pred)
#print(sum(mse)/len(mse))
#print('num of pc: ', i, ' mse: ', sum(mse)/len(mse) )

[array([5.40998892]), array([3.79212815]), array([3.48263455]), array([4.82987738]), array([2.65481329]), array([4.64545624]), array([4.70936771]), array([4.23145095]), array([5.13297299]), array([4.20153412]), array([2.85025321]), array([4.32107533]), array([4.85817505]), array([5.16070147]), array([4.69335427]), array([4.10771742]), array([2.60632028]), array([2.60455966]), array([4.48365105]), array([3.81017368]), array([6.54103271]), array([4.73986708]), array([4.88237168]), array([3.63503089]), array([5.80726549]), array([5.84494132]), array([5.6717221]), array([4.20472495]), array([4.22845609]), array([4.13249331]), array([4.44501769]), array([4.1498327]), array([4.15808218]), array([4.27829657]), array([4.00431406]), array([3.63449432]), array([3.71963512]), array([4.48551806]), array([4.13061611]), array([5.90590564]), array([4.53075645]), array([4.0915509]), array([5.97762483]), array([5.05396166]), array([4.70669428]), array([7.35665155]), array([4.97799631]), array([5.28687431]), array([3.9679534]), array([4.77493818]), array([2.63129506]), array([3.92426179]), array([4.47012164]), array([4.60216436]), array([4.41643844]), array([5.07016076]), array([4.60698089]), array([6.72308601]), array([4.4793795]), array([4.96186391]), array([4.51813271]), array([4.56613552]), array([4.63630501]), array([4.46376159]), array([3.89688529]), array([4.73065042]), array([4.70518878]), array([5.35329623]), array([3.6165675]), array([4.05250352]), array([4.09423786]), array([4.90103113]), array([5.03654289]), array([4.58392183]), array([4.72210309]), array([4.09285747]), array([3.9028671]), array([3.86647862]), array([5.83649685]), array([4.12217127]), array([4.32789461]), array([3.88191239]), array([3.35854126]), array([3.9665711]), array([3.20913961]), array([4.59745323]), array([4.26625065]), array([2.88035542]), array([4.48281723]), array([5.12186769]), array([4.4972999]), array([5.021546]), array([3.80046638]), array([3.33499069]), array([4.76767369]), array([3.0020852]), array([5.2101598]), array([6.05245307]), array([4.36412344]), array([4.64155099]), array([5.8535503]), array([6.0474327]), array([5.48392385]), array([4.2052558]), array([3.60013791]), array([4.11117587]), array([4.60035115]), array([4.28292298]), array([2.94119396]), array([3.78000424]), array([3.36022192]), array([4.06037531]), array([3.90571057]), array([4.25783936]), array([4.00348265]), array([4.78881269]), array([4.30691854]), array([4.57317433]), array([4.12733793]), array([4.7103318]), array([6.27119274]), array([3.96589859]), array([3.91586938]), array([4.72110705]), array([4.2961958]), array([4.71096021]), array([6.59720026]), array([3.52012371]), array([4.62677828]), array([2.59817744]), array([4.14006554]), array([2.66062425]), array([4.38066506]), array([4.5204065]), array([4.32248304]), array([5.25967041]), array([4.08533601])]

In [27]:
# y_pred is the original prediction value 
mse = []
for i in range(80):
    each = y_pred[i]
    #print(each)
    mse.append(mean_squared_error(y_before.iloc[test_index], each))
print(len(mse))
print(sum(mse)/len(mse))

80
0.7383876578339439

### use the original data

In [28]:
columns_name2 = []
for j in range(0, len(normalized_data.columns)-1):
    name = 'feature'+ str(j)
    columns_name2.append(name)
#columns_name2

In [29]:
y = normalized_data['score']
X = normalized_data[columns_name2]
X

,feature0,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,...,feature24647,feature24648,feature24649,feature24650,feature24651,feature24652,feature24653,feature24654,feature24655,feature24656
0,0.024195,-0.595581,-0.268840,-0.114402,-0.414022,-0.370464,-0.606081,-0.477375,-0.661426,1.691496,...,-0.478370,-0.273148,-0.966157,2.635572,-1.216972,1.017995,-0.873492,-1.942849,2.153681,0.005307
1,0.019075,0.003637,-0.005734,0.013134,0.003693,0.007518,-0.007040,-0.005823,-0.014546,-0.000127,...,-0.453192,-0.759260,-0.640716,-0.988034,0.288321,-0.611172,0.268482,0.847671,1.225785,-0.416442
2,0.019075,0.003637,-0.005734,0.013134,0.003693,0.007518,-0.007040,-0.005823,-0.014546,-0.000127,...,-0.541078,-0.410848,1.329214,-0.439547,1.364245,-0.588898,-0.051788,-0.984184,1.452501,-0.315946
3,0.019075,0.003637,-0.005734,0.013134,0.003693,0.007518,-0.007040,-0.005823,-0.014546,-0.000127,...,-0.468753,-0.518949,-0.530444,0.049958,-0.493745,-0.075611,2.076526,0.769073,-0.296060,-0.463321
4,0.114466,-1.071595,-0.616517,-0.501477,-1.210005,-0.843715,0.394804,-0.051286,-1.109841,-0.716376,...,0.186641,0.002331,-0.005212,-0.025318,0.008153,0.009896,0.012708,-0.002056,-0.022357,0.005307
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,0.019075,0.003637,-0.005734,0.013134,0.003693,0.007518,-0.007040,-0.005823,-0.014546,-0.000127,...,-0.468753,-1.285265,2.665347,-1.151590,1.185379,-0.626968,-0.522492,-1.428084,-0.041041,-0.463321
133,-1.833200,0.054212,-0.656037,-0.471369,1.529156,0.851216,1.836981,-0.131820,0.051387,-1.730183,...,-0.469561,1.155136,-0.556891,0.327264,-1.052882,-0.296544,-0.401590,-1.269820,1.089794,0.500035
134,-1.384147,-1.343337,-1.962952,-1.126680,2.055011,2.217349,-1.382617,3.749066,-1.120391,-1.919105,...,0.186641,0.002331,-0.005212,-0.025318,0.008153,0.009896,0.012708,-0.002056,-0.022357,0.005307
135,0.596018,-0.098552,-0.768465,-0.895304,1.952574,-1.381936,-0.186490,-1.126266,-1.131925,-0.023877,...,0.186641,0.002331,-0.005212,-0.025318,0.008153,0.009896,0.012708,-0.002056,-0.022357,0.005307
136,0.019075,0.003637,-0.005734,0.013134,0.003693,0.007518,-0.007040,-0.005823,-0.014546,-0.000127,...,0.186641,0.002331,-0.005212,-0.025318,0.008153,0.009896,0.012708,-0.002056,-0.022357,0.005307

In [ ]:
loo = LeaveOneOut()
loo.get_n_splits(X)


y_pred = []
for train_index, test_index in loo.split(X):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train = X.iloc[train_index]
    X_test = X.iloc[test_index]
    y_train = y.iloc[train_index]
    y_test = y.iloc[test_index]
    print(y_test)
    
    
    regr = RandomForestRegressor(max_depth=2, random_state=0)
    regr.fit(X_train, y_train)

    #y_pred = regr.predict(X_test)
    y_pred.append(regr.predict(X_test)*std + avg)
    
    #print(test_index, y_pred, y_before.iloc[test_index])
    #mse.append(mean_squared_error(y_test, y_pred))
print(y_pred)
#print(sum(mse)/len(mse))
#print('num of pc: ', i, ' mse: ', sum(mse)/len(mse) )

0    1.480059
Name: score, dtype: float64
1   -0.024865
Name: score, dtype: float64
2   -0.024865
Name: score, dtype: float64
3    0.200693
Name: score, dtype: float64
4   -1.588849
Name: score, dtype: float64
5   -0.024865
Name: score, dtype: float64
6   -0.024865
Name: score, dtype: float64
7    1.086115
Name: score, dtype: float64
8    0.58099
Name: score, dtype: float64
9   -1.44435
Name: score, dtype: float64
10   -0.024865
Name: score, dtype: float64
11   -0.024865
Name: score, dtype: float64
12   -0.024865
Name: score, dtype: float64
13    1.177532
Name: score, dtype: float64
14   -0.024865
Name: score, dtype: float64
15   -2.096819
Name: score, dtype: float64
16   -0.024865
Name: score, dtype: float64
17   -0.024865
Name: score, dtype: float64
18   -0.024865
Name: score, dtype: float64
19    0.397675
Name: score, dtype: float64
20   -0.024865
Name: score, dtype: float64
21   -0.024865
Name: score, dtype: float64
22   -0.024865
Name: score, dtype: float64
23   -0.024865
Name: score, dtype: float64
24   -0.900042
Name: score, dtype: float64
25    2.288288
Name: score, dtype: float64
26   -0.322499
Name: score, dtype: float64
27    2.078865
Name: score, dtype: float64
28   -0.024865
Name: score, dtype: float64
29   -0.024865
Name: score, dtype: float64
30   -0.024865
Name: score, dtype: float64
31    1.711192
Name: score, dtype: float64
32   -1.760886
Name: score, dtype: float64
33   -1.149177
Name: score, dtype: float64
34   -2.054035
Name: score, dtype: float64
35   -2.080278
Name: score, dtype: float64
36    0.530844
Name: score, dtype: float64
37   -0.53259
Name: score, dtype: float64
38    0.186959
Name: score, dtype: float64
39   -1.870301
Name: score, dtype: float64
40   -0.024865
Name: score, dtype: float64
41   -0.861743
Name: score, dtype: float64
42   -0.024865
Name: score, dtype: float64
43   -0.024865
Name: score, dtype: float64
44    0.818942
Name: score, dtype: float64
45   -0.900676
Name: score, dtype: float64
46   -0.024865
Name: score, dtype: float64
47   -1.523558
Name: score, dtype: float64
48   -0.286016
Name: score, dtype: float64
49   -0.024865
Name: score, dtype: float64
50   -0.077214
Name: score, dtype: float64
51    1.188735
Name: score, dtype: float64
52   -0.024865
Name: score, dtype: float64
53   -1.60511
Name: score, dtype: float64
54    1.008506
Name: score, dtype: float64
55    0.13147
Name: score, dtype: float64
56    0.532019
Name: score, dtype: float64
57   -0.024865
Name: score, dtype: float64
58   -0.024865
Name: score, dtype: float64
59   -0.024865
Name: score, dtype: float64
60   -0.406993
Name: score, dtype: float64
61    1.753734
Name: score, dtype: float64
62   -0.024865
Name: score, dtype: float64
63    0.987449
Name: score, dtype: float64
64    1.841777
Name: score, dtype: float64
65   -0.024865
Name: score, dtype: float64
66    0.373395
Name: score, dtype: float64
67   -1.282543
Name: score, dtype: float64
68    0.406091
Name: score, dtype: float64
69   -1.931948
Name: score, dtype: float64
70    0.162748
Name: score, dtype: float64
71   -0.024865
Name: score, dtype: float64
72    1.156372
Name: score, dtype: float64
73   -0.024865
Name: score, dtype: float64
74    0.668304
Name: score, dtype: float64
75   -0.024865
Name: score, dtype: float64
76    0.309918
Name: score, dtype: float64
77   -0.024865
Name: score, dtype: float64
78   -0.024865
Name: score, dtype: float64
79   -0.024865
Name: score, dtype: float64
80   -0.024865
Name: score, dtype: float64
81   -0.024865
Name: score, dtype: float64
82    0.101739
Name: score, dtype: float64
83   -0.024865
Name: score, dtype: float64
84   -0.024865
Name: score, dtype: float64
85   -0.024865
Name: score, dtype: float64
86   -1.094252
Name: score, dtype: float64
87   -2.044366
Name: score, dtype: float64
88   -0.024865
Name: score, dtype: float64
89   -0.024865
Name: score, dtype: float64
90    0.866932
Name: score, dtype: float64
91   -1.592139
Name: score, dtype: float64
92   -0.024865
Name: score, dtype: float64
93    1.316511
Name: score, dtype: float64
94    0.700515
Name: score, dtype: float64
95   -0.024865
Name: score, dtype: float64
96   -2.111505
Name: score, dtype: float64
97   -0.024865
Name: score, dtype: float64

In [ ]:
# y_pred is the original prediction value 
mse = []
for i in range(80):
    each = y_pred[i]
    #print(each)
    mse.append(mean_squared_error(y_before.iloc[test_index], each))
print(len(mse))
print(sum(mse)/len(mse))